package com.example.backendredu.alumno.domain;

public enum Carrera {
    SISTEMAS_DE_INFORMACION,
    CIENCIA_DE_DATOS,
    CIENCIA_DE_LA_COMPUTACION,
    CIBERSEGURIDAD,
    ADMINISTRACION_Y_NEGOCIOS_DIGITALES,
    ADMINISTRACION_Y_NEGOCIOS_SOSTENIBLES,
    BUSINESS_ANALYTICS,
    INGENIERIA_INDUSTRIAL,
    BIOINGENERIA,
    INGENERIA_DE_LA_ENERGIA,
    INGENERIA_QUIMICA,
    INGENERIA_AMBIENTAL,
    INGENERIA_CIVIL,
    INGENERIA_ELECTRONICA,
    INGENERIA_MECATRONICA
}
