package com.example.backendredu.alumno.domain;

public enum Carrera {
    SISTEMAS_DE_INFORMACION,
    CIENCIA_DE_DATOS,
    CIENCIA_DE_LA_COMPUTACION,
    CIBERSEGURIDAD,
    ADMINISTRACION_Y_NEGOCIOS_DIGITALES,
    ADMINISTRACION_Y_NEGOCIOS_SOSTENIBLES,
    BUSINESS_ANALYTICS,
    INGENIERIA_INDUSTRIAL,
    BIOINGENIERIA,
    INGENIERIA_DE_LA_ENERGIA,
    INGENIERIA_QUIMICA,
    INGENIERIA_AMBIENTAL,
    INGENIERIA_CIVIL,
    INGENIERIA_ELECTRONICA,
    INGENIERIA_MECATRONICA
}
